Revert "Update `.gitignore` to exclude everything except `recipe/` and `conda-forge.yml`"
conda-forge/conda-smithy pull request #1818
Opened 2023-12-23 07:39 UTC by xhochy

Currently, all builds using `maturin` are broken due to this change. As there seems to be no easy workaround, I would rather revert this and have a more in-depth discussion to avoid the issues stemming from it (e.g. we could also adapt our folder placements in the linux containers).

For more context see https://github.com/conda-forge/pydantic-core-feedstock/pull/82

Checklist
* [x] Added a ``news`` entry

cc @hmaarrfk

2023-12-23 08:11 UTC, isuruf commented
Where in maturin is the gitignore file used?

2023-12-23 09:16 UTC, xhochy commented
The PR that introduced the behavior is https://github.com/PyO3/maturin/pull/695 but this only refers to other internals. I have seen other issues asking on how to solve it but they are all open/unaddressed.

2023-12-23 09:23 UTC, xhochy commented
There is the following option to set something on a per-project basis: https://github.com/PyO3/maturin/commit/ee86fd885b403e2770f13abea9b41329dd5ca280

But, I think that this issue will not be limited to maturin. A lot of other tools (we just had a similar issue internally with rattler-build) also read the gitignore file for copying files to a destination. We should find a more general solution where a .gitignore does not pollute into the recipe build.

2023-12-23 09:43 UTC, davidhewitt commented
cc @messense

There might be an argument that `maturin` should not be reading a `.gitignore` below the repository root? Though I guess based on what you say about `rattler-build`, it sounds like a lot of tools do this, whether it's correct or not.

2023-12-23 09:49 UTC, xhochy commented
The rattler-build issue has been something different but probably using the same code path. We had am internal .gitignore that meant that rattler-build didn't copy the .git folder and thus setuptools_scm no longer worked. 

For me, this was simply an example of "this problem is not limited to maturin".

2023-12-23 10:04 UTC, hmaarrfk approved these changes

2023-12-23 13:10 UTC, mbargull approved these changes
Having tools look arbitrarily up in the filesystem hierarchy is pretty annoying...
The changes to `.gitignore` from gh-1413 are very good and helpful for maintenance.

But I agree, let's revert this for now and later make changes to properly separate the build directories.
The necessary changes are likely to touch `conda-forge-ci-setup` too, so let's do this in an orderly fashion after the holidays and make a new patch release in the interim.

2023-12-23 13:48 UTC, isuruf requested changes
Can't we just do https://github.com/conda-forge/pydantic-core-feedstock/pull/84 ?

2023-12-23 14:07 UTC, mbargull commented
> Can't we just do [conda-forge/pydantic-core-feedstock#84](https://github.com/conda-forge/pydantic-core-feedstock/pull/84) ?

No, if we pick and choose that fine-grained, we have to consider things like
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/e403f01fd447e48ba3a777a9b642354ab1b7e746/recipe/meta.yaml#L23
which would break.
Yes, that file could also be bound.
And yes, that's a brittle thing to do generally.
Point is, IDK what else non-standard stuff is out there.

2023-12-23 14:46 UTC, xhochy commented
We also need ti adjust how build-locally.py works in macOS as this also places the build directory below the feedstock root. There are a multitude of problems where this will come up.

2023-12-23 15:48 UTC, hmaarrfk commented
My understanding is that xhochy is suggesting:

1. We revert
2. We reorganize hierchy
3. We reconsider reinstating it later.

Thr side effect caused by the current strategy took me 2-3 hours to troubleshoot with the help of two other very adept programmers. 

Let's avoid this problem poping up when many of us  may be trying to be away from our computers around the new years.

2023-12-23 15:59 UTC, erykoff commented
I think the problem (if problem is the right word) is that the “ignore” file walker by default uses all parent gitignores https://docs.rs/ignore/latest/src/ignore/walk.rs.html#707 and this is used by maturin here https://github.com/PyO3/maturin/blob/1d7ad9da746fb252bb9c23e76c5df4a36c616c2a/src/source_distribution.rs#L536. 

Also maturin is not the only rust tool that uses this. So there could other places that can behave strangely with new gitignores living anywhere in the parent directory tree.

2023-12-24 01:49 UTC, isuruf commented
https://github.com/conda-forge/pydantic-core-feedstock/pull/86 brings back the old behaviour for the `build_artifacts` directory

2023-12-24 10:05 UTC, isuruf commented
See https://github.com/conda-forge/conda-smithy/pull/1819

2023-12-28 14:13 UTC, isuruf commented
Superseded by #1819

2023-12-28 14:13 UTC, closed without merging