Change default build tool to conda-build again
conda-forge/conda-smithy pull request #1844
Opened 2024-02-20 16:51 UTC by mbargull

Checklist
* [ ] Added a ``news`` entry

I'd like us to get the [fixes from `conda-build=24.1.2` in which also affect `conda-build=3.28.4`](https://github.com/conda/conda-build/blob/24.1.2/CHANGELOG.md#2412-2024-02-15) which we are currently limited to due to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/657 / https://github.com/mamba-org/boa/issues/392 .
If we change to `conda-build` by default, we can avoid the constraint needed for `boa=0.16.0`.
(We should also put out a `boa=0.16.1` for feedstocks that have `conda-mambabuild` set explicitly, of course.)

2024-02-20 16:56 UTC, beckermr requested changes
I am for this, but we need to put a pin somewhere to ensure the latest version is used. There were some bugs which is why re rolled this back last I checked.

2024-02-20 18:29 UTC, mbargull commented
> I am for this, but we need to put a pin somewhere to ensure the latest version is used.

I guess shove a `conda-build>=24.1` into `remote_ci_setup` so that the user can override it when needed, right?

> There were some bugs which is why re rolled this back last I checked.

https://github.com/conda-forge/conda-smithy/issues/1805
Yep, there were some oddities with `conda-build` using legacy code paths such that it didn't play well with `conda-libmamba-solver`; we've added some changes to `conda`/`conda-libmamba-solver` in November to fix that.

2024-02-20 18:34 UTC, beckermr commented
Yes I think so or we can have it as a constraint on our ci setup package.

2024-02-21 00:20 UTC, h-vetinari commented
> If we change to `conda-build` by default, we can avoid the constraint needed for `boa=0.16.0`.

Not against this change, but just wanted to note that we could also (try to) backport the fix for https://github.com/mamba-org/boa/issues/392 to unblock that constraint.

2024-02-21 06:50 UTC, jakirkham commented
> Yes I think so or we can have it as a constraint on our ci setup package.

Are we guaranteed to get the latest `conda-forge-ci-setup` when installing?

If not, maybe adding it here is easiest (though no objections to doing both)

2024-02-21 12:35 UTC, beckermr commented
Yeah let's add it here. Good idea!

2024-02-21 17:00 UTC, mbargull commented
Conceptually, I think `conda-forge-ci-setup` would be a nicer place for it (yes, we'd need to then have `conda-forge-ci-setup=4,>={version with lower bound on conda-build}` in `remote_ci_setup` here then), but for now, I'd also guess it's fine to add it here (done in the latest commit) and would postpone conceptual discussion currently.

2024-02-21 20:02 UTC, beckermr commented
I agree. What's nice here is that people can override easily.

2024-02-21 20:03 UTC, beckermr approved these changes

2024-02-21 20:09 UTC, xhochy approved these changes

2024-02-21 20:11 UTC, merged

2024-02-21 20:16 UTC, jakirkham commented
Thanks all! 🙏

Should we make a new release ( https://github.com/conda-forge/conda-smithy/issues/1845 )?

2024-02-21 20:52 UTC, mbargull commented
Thanks for the reviews!

2024-02-21 21:12 UTC, h-vetinari commented
> Should we make a new release ( #1845 )?

Give me a short time to make a minimal PR for #1840 please (just adding the comprehension for stdlib jinjas), so that - ideally - we won't have to release separately for that.