Add dependabot configuration
conda-forge/conda-smithy pull request #1930
Opened 2024-05-14 08:23 UTC by jaimergp

Checklist
* [ ] Added a ``news`` entry

Trying this out. I'm expecting this config to do the following:

- Update the workflows under `.github/workflows` as usual
- Maaaaybe pick the `github-actions.yml.tmpl` file in the templates. If that's true, we should see a PR updating `upload-artifacts`.

2024-05-14 08:30 UTC, jaimergp commented
I don't think we'll be lucky with the template... [Dependabot parses the YAML](https://github.com/dependabot/dependabot-core/blob/5d60fd0b3a28a598fd9e977c562290871766d29a/github_actions/lib/dependabot/github_actions/file_parser.rb#L47).

2024-05-20 12:03 UTC, beckermr commented on .github/dependabot.yml
> +      interval: "weekly"
monthly would be better. IDK what the syntax is though.

2024-05-20 12:04 UTC, beckermr requested changes
See above.

2024-05-20 12:38 UTC, jaimergp commented
Addressed.

2024-05-20 12:50 UTC, beckermr submitted a review, later dismissed
We should not merge this. The goal with our CI is to ensure things are reproducible including rendering with smithy.

2024-05-20 16:52 UTC, beckermr approved these changes

2024-05-21 09:46 UTC, merged