feat: add lint for recipe name
conda-forge/conda-smithy pull request #2000
Opened 2024-07-29 13:30 UTC by nichmor

Checklist
* [ ] Added a ``news`` entry
* [ ] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

2024-07-29 13:36 UTC, wolfv approved these changes

2024-07-29 13:37 UTC, wolfv commented
looks good. @nichmor maybe we should also send a PR that adds mypy to pre-commit?

2024-07-29 14:16 UTC, nichmor commented
I like the idea!

2024-07-30 07:20 UTC, wolfv commented on conda_smithy/linter/rattler_linter.py
> +def lint_package_name(
That is correct. I think `rattler-build` also never accepts a package with an invalid name so it should basically never build successfully (which makes the lint a little less important for the rattler-build case).

2024-07-30 07:21 UTC, nichmor commented on conda_smithy/linter/rattler_linter.py
> +def lint_package_name(
can we skip in this case linting of the package name?

2024-07-30 11:38 UTC, beckermr commented on conda_smithy/linter/rattler_linter.py
> +def lint_package_name(
We only need to check the package section, not the context one.

2024-07-30 11:41 UTC, wolfv commented on conda_smithy/linter/rattler_linter.py
> +def lint_package_name(
Yes, but to properly lint the name we need to evaluate the jina, right?

We also need to double check that this works for multi-output recipes.

2024-07-30 11:41 UTC, wolfv commented on conda_smithy/linter/rattler_linter.py
> +def lint_package_name(
But more generally, rattler-build wouldn't allow you to build a package with an illegal name, so this lint might not be necessary. Do you still want it. @beckermr?

2024-07-30 12:38 UTC, beckermr commented on conda_smithy/linter/rattler_linter.py
> +def lint_package_name(
For v1 recipes we render the jinja2 before linting. We need to do the same for v2 recipes as well.

2024-08-05 08:44 UTC, nichmor commented
@beckermr  added test that validates linting of recipe name using context value

2024-08-05 11:06 UTC, beckermr commented on tests/test_lint_recipe.py
> +            "package": {"name": "${{ name }}"},
```suggestion
            "context": {"blah": "mp++"},
            "package": {"name": "${{ blah }}"},
```

2024-08-05 11:06 UTC, beckermr requested changes
One nit to make the tests more robust.

2024-08-05 11:10 UTC, beckermr commented
I've add a news file we can add items to as we merge PRs.

2024-08-05 12:17 UTC, merged