feat: wip on noarch and runtime deps
conda-forge/conda-smithy pull request #2001
Opened 2024-07-30 07:04 UTC by nichmor

Checklist
* [ ] Added a ``news`` entry
* [ ] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

2024-07-31 14:08 UTC, beckermr requested changes
We do allow platform-only selectors in noarch recipes. Our current linter should have that edge case as a guide.

2024-08-05 13:15 UTC, nichmor commented
> We do allow platform-only selectors in noarch recipes. Our current linter should have that edge case as a guide.

added lint for noarch platforms use-case. could you please take a look?

2024-08-05 17:55 UTC, wolfv commented
Fixed up the merge conflicts and rebased on main.

2024-08-05 20:55 UTC, beckermr requested changes
One nit.

2024-08-05 20:55 UTC, beckermr commented on news/2001-lint-noarch-deps.rst
> +* add lint for noarch and runtime deps (#2001)
Let's add this the single item we already have going.

2024-08-05 21:01 UTC, merged