fix: remove example recipe.yaml lint
conda-forge/conda-smithy pull request #2036
Opened 2024-08-13 07:42 UTC by nichmor

Checklist
* [ ] Added a ``news`` entry
* [ ] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

Right now we don't have recipe.yaml in our example folder, but we lint for it. 
This lint should be removed

2024-08-13 08:55 UTC, beckermr requested changes
Why not just add an example to stages recipes? Otherwise we'll have to add back this lint later.

2024-08-13 08:58 UTC, baszalmstra commented
There are [two examples in staged recipes now](https://github.com/conda-forge/staged-recipes/tree/main/recipes), does this properly handle both cases?

2024-08-13 09:16 UTC, zklaus commented
The example `recipe.yaml` is in a different folder, namely `example-new-recipe`.

2024-08-13 09:20 UTC, beckermr commented
Let's put it in the same folder or adjust the path once in smithy.

2024-08-13 09:46 UTC, nichmor commented
My initial thought was that right now we disabled publishing on main channel and to not to confuse our users that there is recipe.yaml as an example but you cannot publish it on the main channel, I decided to remove the lint temporarily.

but I agree with you, let me move it to the same folder

2024-08-14 16:40 UTC, jaimergp commented on conda_smithy/lint_recipe.py
> -            )
Why not this instead?

```python
for example_path in (("example", "meta.yaml"), ("example-v1", "recipe.yaml")):
    example_fname = os.path.abspath(os.path.join(recipe_dir, "..", *example_path))
```

And then adjust the f-string in the error msg to point to `os.path.join("recipes", *example_path)`?

2024-08-14 16:48 UTC, jaimergp commented
Also needs a `news/` item.

2024-08-14 18:33 UTC, isuruf commented
Since we have https://github.com/conda-forge/staged-recipes/blob/main/.github/workflows/do_not_edit_example.yml do we even need this lint?

2024-08-20 14:11 UTC, beckermr commented
Agreed @isuruf. We should remove to help make smithy more stable and independent of staged-recipes.

2024-08-20 14:15 UTC, beckermr commented
See https://github.com/conda-forge/conda-smithy/pull/2038

2024-08-22 18:52 UTC, closed without merging