allow equal-signs in CFEP-25 pins
conda-forge/conda-smithy pull request #2167
Opened 2024-11-24 20:45 UTC by h-vetinari

The original [version](https://github.com/conda-forge/cfep/pull/56) of CFEP-25 used:
```yaml
test:
  requires:
    - python ={{ python_min }}
```
This is a natural an allowed syntax in conda, as is 
```yaml
test:
  requires:
    - python =={{ python_min }}
```
We shouldn't spuriously lint on those, hence allow equal signs in the pattern.

2024-11-24 22:18 UTC, beckermr requested changes
We needed a smithy and conda build fix due to the equal signs. Once we have conda build 24.11 merged, let's retest before we merge this one.

2024-11-26 12:57 UTC, beckermr commented
This PR https://github.com/conda/conda-build/pull/5555 fixes the issue (and I tested it live on a feedstock). We'll need to wait until 25.1.0 to see the fix live.

2024-11-26 20:59 UTC, h-vetinari commented
> This PR [conda/conda-build#5555](https://github.com/conda/conda-build/pull/5555) fixes the issue (and I tested it live on a feedstock). We'll need to wait until 25.1.0 to see the fix live.

Cool, thanks a lot! (and nice PR number! 😁)

2025-02-28 15:49 UTC, beckermr approved these changes

2025-02-28 15:52 UTC, merged